### ISSUE TITLE
Dockerfile moves files to wrong location

### ISSUE THREAD

**Issue by rabidscorpio** [disaster37/activemq-kube#1]
Hi, this is a bug here, this will move both the tar.gz file and the apache-activemq-X.XX.X directory into `/opt/activemq` so then the `bin` directory becomes `/opt/activemq/apache-activemq-X.XX.X/bin` instead of `/opt/activemq/bin`.
https://github.com/disaster37/activemq-kube/blob/a442a60c364d0d2cf601eca905d8bcf3910f1d34/docker/Dockerfile#L25
That means when you use sed on a conf file a few lines down, that file won't be in `/opt/activemq/conf`:
https://github.com/disaster37/activemq-kube/blob/a442a60c364d0d2cf601eca905d8bcf3910f1d34/docker/Dockerfile#L29

**Comment by disaster37** [comment]
I not really understand that you need.
You can check it by:

```
docker run -ti webcenter/activemq-kube:5.16.0 ls /opt/activemq
```
